apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-autocd-test-1-xgra
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: Y0a49uu3rMGyCOYT9ttkt1nTdkDB3wQllVm2o6KyCwlf1UGhDig+jXhZ/p+vm6M/WNtkdnf/0kn7WGEayJrbQGNeio/eaepE7TV4Db3lqDRwSFzsZKWrbvjIYssUlrdH

---
apiVersion: v1
kind: Service
metadata:
  name: autocd-test-1-xgra
  namespace: default
  labels:
    app: autocd-test-1-xgra
spec:
  type: ClusterIP
  selector:
    app: autocd-test-1-xgra
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocd-test-1-xgra
  namespace: default
  labels:
    app: autocd-test-1-xgra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocd-test-1-xgra
  template:
    metadata:
      labels:
        app: autocd-test-1-xgra
    spec:
      serviceAccountName: scoutflo-sa-autocd-test-1-xgra
      containers:
        - name: autocd-test-1-xgra-container
          image: 296062577626.dkr.ecr.ap-south-1.amazonaws.com/welcome-scoutflo:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          env: []

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autocd-test-1-xgra
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: autocd-test-1-sdseai3xhmv23n5xzlgwy73a-irujd.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autocd-test-1-xgra
                port:
                  number: 80
  tls:
    - hosts:
        - autocd-test-1-sdseai3xhmv23n5xzlgwy73a-irujd.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
